-- Criação das Tabelas
CREATE TABLE INSCRICOES (
    ID_INSCRICAO INT PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    TRUST_SCORE INT DEFAULT 100
);

CREATE TABLE LOG_AUDITORIA (
    ID_LOG INT PRIMARY KEY,
    ID_INSCRICAO INT,
    MOTIVO_CANCELAMENTO VARCHAR(255),
    DATA_EVENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_INSCRICAO) REFERENCES INSCRICOES(ID_INSCRICAO)
);

-- Gerador de IDs para o Log
CREATE SEQUENCE SEQ_LOG START WITH 1 INCREMENT BY 1;

-- Carga de Teste
INSERT INTO INSCRICOES VALUES (1, 'Ana Silva', 'ana.silva@gmail.com', 'PENDING', 100);
INSERT INTO INSCRICOES VALUES (2, 'Bot Maligno', 'user123@fake.com', 'PENDING', 100);
INSERT INTO INSCRICOES VALUES (3, 'Spammer', 'temp-mail-99@temp-mail.org', 'PENDING', 100);
INSERT INTO INSCRICOES VALUES (4, 'Erro Humano', 'email_sem_arroba.com', 'PENDING', 100);
INSERT INTO INSCRICOES VALUES (5, 'Carlos Tech', 'carlos@cyber.com', 'PENDING', 100);

-- Query de Varredura Anti-Bot
INSERT INTO LOG_AUDITORIA (ID_LOG, ID_INSCRICAO, MOTIVO_CANCELAMENTO)
SELECT SEQ_LOG.NEXTVAL, ID_INSCRICAO, 'Fraude detectada: Domínio suspeito ou malformado'
FROM INSCRICOES WHERE STATUS = 'PENDING' 
AND (EMAIL LIKE '%@fake.com' OR EMAIL LIKE '%@temp-mail%' OR EMAIL NOT LIKE '%@%');

UPDATE INSCRICOES SET STATUS = 'CANCELED', TRUST_SCORE = TRUST_SCORE - 15
WHERE STATUS = 'PENDING' 
AND (EMAIL LIKE '%@fake.com' OR EMAIL LIKE '%@temp-mail%' OR EMAIL NOT LIKE '%@%');

COMMIT;
